### ISSUE TITLE
Incorrect goroutine of execution in Chapter 8 session Example: Concurrent Echo Server

### ISSUE THREAD

**Issue by anhdat** [shichao-an/notes#1]
In this session at:
https://notes.shichao.io/gopl/ch8/#example-concurrent-echo-server

We have the example of reverb:
```go
func handleConn(c net.Conn) {
    input := bufio.NewScanner(c)
    for input.Scan() {
        echo(c, input.Text(), 1*time.Second)
    }
    // NOTE: ignoring potential errors from input.Err()
    c.Close()
}
```
This snippet will have blocking echo, and the text explains:
>The arguments to the function started by go are evaluated when the go statement itself is executed; thus input.Text() is evaluated in the main goroutine.

But in fact, the `handleConn` is executed in a separated goroutine that's spawned from main goroutine. So it should be clear that `input.Text()` is executed from that goroutine rather than the main one.

Please correct me if I'm wrong. I'm new to Go and reading this part causes me confused.
Thanks.

**Comment by shichao-an** [comment]
Hi @anhdat,

It seems the author forgot that `handleConn` is executed in a goroutine rather than the main goroutine. He should mean "thus input.Text() is evaluated in the <s>main</s> current goroutine".
