### ISSUE TITLE
Copyright Infringement?

### ISSUE THREAD

**Issue by brendangregg** [shichao-an/notes#12]
docs/spec contains material that looks verbatim from my book Systems Performance: Enterprise and the Cloud. I understand it is possible to quote excerpts for use, and there is a threshold beyond which it is copyright infringement. I can ask my publisher to investigate, but I'll ask you first: what your thoughts are on this?

**Comment by shichao-an** [comment]
Hi Brendan,

Thank you for bringing this up. I have [deleted all contents and history](https://help.github.com/en/articles/removing-sensitive-data-from-a-repository) under "spec". Sorry for any copyright concerns it have induced.

**Comment by bringhurst** [comment]
It looks like a large portions of the CPU scheduler pages also appear to be copied verbatim from @r-love’s kernel book.

**Comment by shichao-an** [comment]
@bringhurst Thank you for bringing this up. I have [deleted all contents and history](https://help.github.com/en/articles/removing-sensitive-data-from-a-repository) under "lkd".

**Comment by anilauece** [comment]
That notes was useful for many people who are interested in linux kernel development. Is it possible to get it back?

**Comment by gf-mse** [comment]
As a purely historical note, the original comment of @bringhurst  looked like that:
`It looks like a large portions of the CPU scheduler pages also appear to be copied verbatim from @r-love’s kernel book. (FYI @github/support).`

**Comment by Delta0001** [comment]
I would love to have this back!

**Comment by realyukii** [comment]
@anilauece totally agreed
